### PR TITLE
Update omi_connector.lua

### PR DESCRIPTION
**Pull request by SomeAverageDev**
fix url value in post request

### CODE REVIEW

**Comment by SomeAverageDev** [comment]
Hello @bouda1, do you think we could manage to get the notes_url related to each event in the content sent from CENTREON ? I don't see the value at LUA level, so I guess this is not possible yet...

**Comment by bouda1** [comment]
Hi @SomeAverageDev 
It's strange that you don't see it at the Lua level. Events sent to Lua connector are a strict copy of events received by centreon-broker.
`notes_url` field should be available in _service_ and _host_ events. So a code like this one should give the answer you expect:
`function write(e)`
`  if e.category == 1 and (e.element == 12 or e.element == 23) then`
`   broker_log:info(0, "we have an host/service with notes_url = " .. tostring(e.notes_url))`
`  end`
`  return true`
`end`

If it is not the case, let me know, I will take a look.
Cheers.

**Comment by SomeAverageDev** [comment]
hello,
thanks for your fast reply,
I am using following versions : "centreon-broker-3.0.16-1.el6.x86_64 /
centreon-engine-1.8.1-1.el6.x86_64 / centreon-2.8.26-3.el6.noarch" (could
be the root cause)

I only get "category=1 & element=24" events (I filtered on "NEB" in broker
configuration)
I have defined an URL at "generic-service" level, the URL shows as expected
in the CENTREON interface, but not in the LUA data.

below a set of JSON data received by the "write" function:

Mon 14 Oct 2019 05:27:18 PM CEST: INFO: DATA:
{"acknowledgement_type":0,"check_attempt":3,"passive_checks":false,"last_state_change":1549633876,"next_check":1571067137,"should_be_scheduled":true,"flap_detection":true,"enabled":true,"host_id":19,"state":2,"last_update":1571066838,"last_check":1571066837,"execution_time":0.175196,"acknowledged":false,"service_id":43,"active_checks":true,"notify":false,"max_check_attempts":3,"obsess_over_service":true,"check_type":0,"last_hard_state_change":1549633876,"output":"Disk
CRITICAL - no output (-p number expected... it doesn't exist, try another
disk
number)\n","category":1,"perfdata":"","check_interval":5,"check_command":"check_centreon_remote_storage!&quot","retry_interval":1,"check_period":"24x7","type":65560,"last_hard_state":2,"state_type":1,"percent_state_change":0,"notification_number":0,"event_handler":"","element":24,"checked":true,"no_more_notifications":false,"event_handler_enabled":true,"flapping":false,"scheduled_downtime_depth":0,"last_time_critical":1571066837,"last_time_unknown":1549633577,"latency":0.074}

Mon 14 Oct 2019 05:27:18 PM CEST: INFO: *d.category = 1, d.element = 24*

thanks !
PS:on peut éventuellement en discuter en français !
Gaël

Le lun. 14 oct. 2019 à 15:37, David Boucher <notifications@github.com> a
écrit :

**Comment by bouda1** [comment]
Thank you.
I have open an issue. If I can reproduce it easily I hope it to be fixed in the next centreon-broker version. But I'm not sure this will be backported to Broker 3.0.16!
Cheers.

**Comment by SomeAverageDev** [comment]
Thanks !
Regarding the notes_url, it might be possible to get the value using an API call to CENTREON from lua script, but it could cause performance issue...
I am also working on downtime management, and I think there is an issue with it, not in the script, but in the logic, as if an alarm happens in downtime it is sent to LUA script (and therefore in OMi), but as there is no state change at the end of the downtime (but still NOK), the event is not sent again to OMi...
For now I don't see how to fix this...

**Pull request merged**
